
export const ALERT_REGISTRATION = 'ALERT_REGISTRATION';
export const HIDE_REGMODAL = 'HIDE_REGMODAL';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_USER = 'SET_USER';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILE';


export const GET_HOTEL = 'GET_HOTEL';
export const GET_ALL_HOTELS = 'GET_HOTELS';
export const HOTEL_NOT_FOUND = 'HOTEL_NOT_FOUND';
export const CLEAR_HOTEL = 'CLEAR_HOTEL';
export const HOTEL_LOADING = 'HOTEL_LOADING';

export const HOLD_HOTEL = 'HOLD_HOTEL';

export const DO_RATING = 'DO_RATING';